apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: finmark

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-secrets.yaml
  - 03-kong.yaml
  - 04-agent-service.yaml
  - 05-llm-gateway.yaml
  - 06-data-service.yaml
  - 07-workflow-service.yaml
  - 08-integration-service.yaml
  - 09-postgres.yaml
  - 10-kong-db.yaml
  - 11-redis.yaml
  - 12-ingress.yaml
  - 13-hpa.yaml
